import { createPgModel } from "../db/pgModel.js";
import { Project } from "./Project.js";
import { Sprint } from "./Sprint.js";
import { User } from "./User.js";

export type TicketStatus = "Backlog" | "To Do" | "In Progress" | "In Review" | "Done";
export type TicketPriority = "low" | "medium" | "high" | "critical";
export type TicketSlaStatus = "healthy" | "due_soon" | "breached" | "resolved";
export interface ITicket { [key: string]: any; organization: string; ticketId: string; title: string; description: string; acceptanceCriteria: string[]; acceptanceCriteriaDone?: boolean[]; status: TicketStatus; priority: TicketPriority; storyPoints: number; assignee?: string; reporter: string; project: string; sprint?: string; epic: string; labels: string[]; dueDate?: Date; blocked: boolean; dependencies: string[]; issueLinks: any[]; comments: any[]; workLogs: any[]; history: any[]; statusTransitions: any[]; watchers: string[]; attachments: any[]; slaPolicy: { firstResponseHours: number; resolutionHours: number }; firstResponseDueAt?: Date; resolutionDueAt?: Date; firstRespondedAt?: Date; resolvedAt?: Date; slaStatus: TicketSlaStatus; rank: number; archivedAt?: Date; createdAt?: Date; updatedAt?: Date }
const json = ["acceptanceCriteria", "acceptanceCriteriaDone", "labels", "dependencies", "issueLinks", "comments", "workLogs", "history", "statusTransitions", "watchers", "attachments", "slaPolicy"];
export const Ticket = createPgModel({ table: "tickets", columns: ["organization", "ticketId", "title", "description", "acceptanceCriteria", "acceptanceCriteriaDone", "status", "priority", "storyPoints", "assignee", "reporter", "project", "sprint", "epic", "labels", "dueDate", "blocked", "dependencies", "issueLinks", "comments", "workLogs", "history", "statusTransitions", "watchers", "attachments", "slaPolicy", "firstResponseDueAt", "resolutionDueAt", "firstRespondedAt", "resolvedAt", "slaStatus", "rank", "archivedAt"], json, defaults: { description: "", acceptanceCriteria: [], acceptanceCriteriaDone: [], storyPoints: 0, epic: "", labels: [], blocked: false, dependencies: [], issueLinks: [], comments: [], workLogs: [], history: [], statusTransitions: [], watchers: [], attachments: [], slaPolicy: { firstResponseHours: 8, resolutionHours: 72 }, slaStatus: "healthy", rank: 0 }, relations: { assignee: { model: () => User }, reporter: { model: () => User }, project: { model: () => Project }, sprint: { model: () => Sprint }, watchers: { model: () => User, many: true } } });
