export const apiCatalog = {
  version: "1.1.0",
  basePath: "/api/v1",
  groups: {
    auth: ["POST /auth/register", "POST /auth/login", "POST /auth/verify-otp", "POST /auth/resend-otp", "POST /auth/refresh", "POST /auth/logout", "GET /auth/me", "POST /auth/forgot-password", "POST /auth/reset-password", "POST /auth/change-password", "PATCH /auth/preferences", "POST /auth/accept-invite", "GET /auth/sessions", "DELETE /auth/sessions/:id"],
    workspaces: ["GET /workspaces", "POST /workspaces", "POST /workspaces/:id/switch", "POST /workspaces/:id/onboarding/complete", "GET /invitations/preview", "GET /invitations/pending"],
    organizations: ["GET /companies", "GET /companies/:companyId/workspaces", "GET /companies/:companyId/members", "POST /companies/:companyId/workspaces", "GET /companies/:companyId/groups", "POST /companies/:companyId/groups", "PATCH /companies/:companyId/groups/:id", "DELETE /companies/:companyId/groups/:id", "PUT /companies/:companyId/groups/:id/members", "PUT /companies/:companyId/groups/:id/workspaces"],
    users: ["GET /me", "GET /team", "POST /team", "GET /roles", "POST /roles", "PATCH /roles/:id", "DELETE /roles/:id", "GET /users", "GET /users/:id", "PATCH /users/:id", "POST /users/:id/deactivate", "POST /users/:id/reactivate", "DELETE /users/:id", "POST /invitations", "POST /invitations/:id/resend", "DELETE /invitations/:id"],
    projects: ["GET /projects", "POST /projects", "GET /projects/:id", "PATCH /projects/:id", "DELETE /projects/:id", "PUT /projects/:id/members", "POST /projects/:id/archive", "POST /projects/:id/restore"],
    planning: ["GET /backlog", "GET /sprints", "POST /sprints", "PATCH /sprints/:id", "DELETE /sprints/:id", "POST /sprints/:id/start", "POST /sprints/:id/complete", "POST /sprints/:id/reopen", "GET /cycles", "POST /cycles", "GET /cycles/:id", "PATCH /cycles/:id", "DELETE /cycles/:id"],
    tickets: ["GET /tickets", "POST /tickets", "GET /tickets/:ticketId", "PATCH /tickets/:id", "DELETE /tickets/:id", "POST /tickets/bulk", "POST /tickets/:id/assign", "PATCH /tickets/:id/status", "PATCH /tickets/:id/rank", "POST /tickets/:id/links", "POST /tickets/:id/archive", "POST /tickets/:id/restore", "POST /tickets/:id/clone", "POST /tickets/:id/watch", "DELETE /tickets/:id/watch", "GET /tickets/:id/history", "POST /tickets/:id/comments", "PATCH /tickets/:id/comments/:commentId", "DELETE /tickets/:id/comments/:commentId", "POST /tickets/:id/work-logs", "PATCH /tickets/:id/work-logs/:logId", "DELETE /tickets/:id/work-logs/:logId", "PATCH /tickets/:id/dependencies", "POST /tickets/:id/attachments", "GET /tickets/attachments/:attachmentId/download", "DELETE /tickets/:id/attachments/:attachmentId"],
    resources: ["GET /resources/:kind", "POST /resources/:kind", "GET /resources/:kind/:id", "PATCH /resources/:kind/:id", "DELETE /resources/:kind/:id"],
    operations: ["GET /notifications", "PATCH /notifications/:id/read", "POST /notifications/read-all", "GET /audit-logs", "GET /audit-logs/export", "GET /integrations/:kind", "POST /integrations/:kind", "DELETE /integrations/:kind/:id", "GET /settings", "PATCH /settings", "GET /sla", "PATCH /sla/policy", "PATCH /organization", "DELETE /organization", "GET /organization/usage", "GET /export", "POST /import", "POST /import/resources", "GET /reports", "GET /reports/cycle-time", "GET /dashboard", "GET /my-work"],
    intelligence: ["POST /analysis/sprint-risk", "GET /analysis/examples", "GET /ai/endpoints", "POST /ai/execute", "GET /ai/models", "GET /ai/conversations", "GET /ai/conversations/:id/messages", "DELETE /ai/conversations/:id", "POST /ai/chat", "POST /ai/generate-tickets", "POST /ai/confirm-ticket-plan"],
  },
};
